### PR TITLE
Fix #139

### LINKED ISSUE #139: Can not lazy load this plugin
@MattesGroeger 

Hi, I am author of SpaceVim, and I just use this plugin in it, in spacevim, all plugins are lazzy loaded. but I found if I make this plugin lazzy load, the auto save does not work, so I read the plugin code. I found:

https://github.com/MattesGroeger/vim-bookmarks/blob/master/plugin/bookmark.vim#L36-L50

```vim
function! s:init(file)
  if g:bookmark_auto_save ==# 1 || g:bookmark_manage_per_buffer ==# 1
    augroup bm_vim_enter
      autocmd!
      autocmd BufEnter * call s:set_up_auto_save(expand('<afile>:p'))
    augroup END
  endif
  if a:file !=# ''
    call s:set_up_auto_save(a:file)
  elseif g:bookmark_manage_per_buffer ==# 0 && g:bookmark_save_per_working_dir ==# 0
    call BookmarkLoad(s:bookmark_save_file(''), 1, 1)
  endif
endfunction

autocmd VimEnter * call s:init(expand('<afile>:p'))
```

you use an autocmd VimEnter to setup the autocmd for autosave. so if the plugin is lazy loaded, this will not be setup.

I will fix it, and try to send a PR.

### PR DESCRIPTION
**Pull request by wsdjeg**

### CODE REVIEW

**Comment by wsdjeg** [comment]
still need some fix, after plugin loaded, the markd should be shown.

**Comment by wsdjeg** [comment]
Done!

**Comment by MattesGroeger** [comment]
Thanks for your contribution. Did you also make sure it works outside spacevim still?

**Comment by wsdjeg** [comment]
@MattesGroeger Yeah, I have test it without spacevim.

**Pull request merged**
