### PR TITLE
Add function and commands to move up/down a bookmark

### PR DESCRIPTION
**Pull request by yuan-**
* Add function and commands to move up/down a bookmark
* Add confirm function when toggle a bookmark with annotation
* Change the WinLeave to VimLeave

### CODE REVIEW

**Comment by MattesGroeger** [comment]
Thanks a lot for your contribution @yuan- ... could you please update the documentation in `Readme.md` and `doc/bookmarks.txt` accordingly?

**Comment by yuan-** [comment]
OK! I will update the Readme.md and doc/bookmarks.txt

**Comment by yuan-** [comment]
I have updated the  Readme.md and doc/bookmarks.txt

**Comment by MattesGroeger** [comment]
Thanks a lot!

**Pull request merged**
